//7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro
// e a sua terça parte.
//Ex:Digite um número: 3.5O dobro de 3.5 é 7.0 A terça parte de 3.5 é 1.16666

Algoritmo "dobro de um numero"

Var
n1, mult,divisao: real



Inicio
escreva("Digite um número: ")
leia(n1)
mult <-n1*2
divisao <- n1/3
escreva("O dobro de ", n1, " é ", mult, " A terça parte de ", n1, " é ",divisao)

Fimalgoritmo