//5) Faça um programa que leia as duas notas de um aluno em uma matéria
// e mostrena tela a sua média na disciplina.
//Ex:Nota 1: 4.5 Nota 2: 8.5 A média entre 4.5 e 8.5 é igual a 6.5

Algoritmo "semnome"

Var
 n1, n2, media : real
 


Inicio
escreva("Qual a sua primeria nota? ")
leia(n1)
escreva("Qual a sua segunda nota? ")
leia(n2)
media<-(n1 + n2) /2
escreva("A média entre ", n1, " e", n2, " é igual a ", media )


Fimalgoritmo