//3) Crie um programa que leia o nome e o salário de um funcionário,
// mostrando nofinal uma mensagem.
//Ex:Nome do Funcionário: Maria do CarmoSalário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.
Algoritmo "salário funcionários"

Var
 salario: real
 nome: caractere
 


Inicio
escreval("Escreva seu nome e seu salário aqui: ")
leia(nome, salario)
escreval("Nome do Funcionário:",nome, " tem um salário de",salario," em Junho.")

Fimalgoritmo