//42)Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!

Algoritmo ""

Var

n, contador:inteiro

Inicio
contador<-0
escreval("Digite um numero inteiro postitivo")
leia(n)
enquanto (contador<=n ) faca
   escreval(contador)
   contador<-contador+1
fimenquanto
escreval("Acabou !")



Fimalgoritmo