Algoritmo "lacosEnquanto-ConversorDolar"

Var
   reais,dolar:real
   contador, quantidade: inteiro

Inicio
   contador <-1

   escreval("Quantas vezes você quer converter?")
   leia(quantidade)

   enquanto (contador<=quantidade) faca
      escreval("Quantos R$ você tem?: ")
      leia(reais)
      dolar<-reais/2,50
      escreval("O valor convertido em $ é de ", dolar)
      contador<- contador+ 1
   fimenquanto




Fimalgoritmo